/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author UnTalNose
 */
public class Principal2 extends javax.swing.JFrame {

    public Principal2() {
        initComponents();
        FrameInterno obj = new FrameInterno();
        obj.show();
        PanelInterno.add(obj);
        try {
            obj.setMaximum(true);
        } catch (Exception e) {
        }
        ConfigVentana();
    }
    
    public void ConfigVentana(){
        this.setSize(1366,730);
        this.setExtendedState(JFrame.MAXIMIZED_HORIZ);
        this.setResizable(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        PanelInterno = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        MenuInicio = new javax.swing.JButton();
        MenuInscripcion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuTienda = new javax.swing.JMenu();
        MenuProductos = new javax.swing.JMenu();
        MenuChecador = new javax.swing.JMenu();
        MenuSeguimiento = new javax.swing.JMenu();
        MenuReportes = new javax.swing.JMenu();
        MenuAdministrador = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JMenuItem();
        MenuNomina = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelInternoLayout = new javax.swing.GroupLayout(PanelInterno);
        PanelInterno.setLayout(PanelInternoLayout);
        PanelInternoLayout.setHorizontalGroup(
            PanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        PanelInternoLayout.setVerticalGroup(
            PanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        MenuInicio.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        MenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoInicio.png"))); // NOI18N
        MenuInicio.setText("Inicio");
        MenuInicio.setAlignmentY(0.0F);
        MenuInicio.setBorderPainted(false);
        MenuInicio.setFocusable(false);
        MenuInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuInicio.setPreferredSize(new java.awt.Dimension(80, 79));
        MenuInicio.setRequestFocusEnabled(false);
        MenuInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInicioActionPerformed(evt);
            }
        });
        jToolBar1.add(MenuInicio);

        MenuInscripcion.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        MenuInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoInscripcion.png"))); // NOI18N
        MenuInscripcion.setText("Inscripción");
        MenuInscripcion.setFocusable(false);
        MenuInscripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuInscripcion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInscripcionActionPerformed(evt);
            }
        });
        jToolBar1.add(MenuInscripcion);

        jMenuBar1.setBorder(null);

        MenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoArchivo.png"))); // NOI18N
        MenuArchivo.setText("Archivo");
        MenuArchivo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jMenuBar1.add(MenuArchivo);

        MenuTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TiendaIconoMe.png"))); // NOI18N
        MenuTienda.setText("Tienda");
        MenuTienda.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        MenuTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTiendaActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuTienda);

        MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProductosIcono.jpg"))); // NOI18N
        MenuProductos.setText("Productos");
        MenuProductos.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        MenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuProductos);

        MenuChecador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RelojIconoMe.png"))); // NOI18N
        MenuChecador.setText("Checador");
        MenuChecador.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jMenuBar1.add(MenuChecador);

        MenuSeguimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SeguimientoIconoM.png"))); // NOI18N
        MenuSeguimiento.setText("Seguimiento");
        MenuSeguimiento.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jMenuBar1.add(MenuSeguimiento);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuReportes.png"))); // NOI18N
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jMenuBar1.add(MenuReportes);

        MenuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuAdmin.png"))); // NOI18N
        MenuAdministrador.setText("Administrador");
        MenuAdministrador.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N

        MenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuariosIconoMenu.png"))); // NOI18N
        MenuUsuarios.setText("Usuarios");
        MenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosActionPerformed(evt);
            }
        });
        MenuAdministrador.add(MenuUsuarios);

        MenuNomina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        MenuNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NominaIconoM.png"))); // NOI18N
        MenuNomina.setText("Nómina");
        MenuNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNominaActionPerformed(evt);
            }
        });
        MenuAdministrador.add(MenuNomina);

        jMenuBar1.add(MenuAdministrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelInterno))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addComponent(PanelInterno)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInicioActionPerformed
        PanelInterno.removeAll();
        FrameInterno obj = new FrameInterno();
        obj.show();
        PanelInterno.add(obj);
        try {
            obj.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MenuInicioActionPerformed

    private void MenuInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInscripcionActionPerformed
        PanelInterno.removeAll();
        Inscripcion obj = new Inscripcion();
        FrameInterno Fram = new FrameInterno();
        Fram.setContentPane(obj.getContentPane());
        Fram.show();
        PanelInterno.add(Fram);
        try {
            Fram.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MenuInscripcionActionPerformed

    private void MenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosActionPerformed
        PanelInterno.removeAll();
        
        Usuarios obj = new Usuarios();
        FrameInterno Fram = new FrameInterno();
        Fram.setContentPane(obj.getContentPane());
        Fram.show();
        PanelInterno.add(Fram);
//        try {
//            Fram.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_MenuUsuariosActionPerformed

    private void MenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosActionPerformed
        Productos obj = new Productos();
        obj.setVisible(true);
        System.out.println("Se Clickeo en Productos");
        
//        FrameInterno Fram = new FrameInterno();
//        Fram.setContentPane(obj.getContentPane());
//        Fram.show();
       
        //PanelInterno.add(Fram);
//        try {
//            Fram.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_MenuProductosActionPerformed

    private void MenuNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNominaActionPerformed

    private void MenuTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
        } catch (Exception e){
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdministrador;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuChecador;
    private javax.swing.JButton MenuInicio;
    private javax.swing.JButton MenuInscripcion;
    private javax.swing.JMenuItem MenuNomina;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuSeguimiento;
    private javax.swing.JMenu MenuTienda;
    private javax.swing.JMenuItem MenuUsuarios;
    private javax.swing.JDesktopPane PanelInterno;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
