package gimnasio;

import static gimnasio.Tienda.Modelo;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Mancilla
 */
public class Seguimiento extends javax.swing.JFrame {

    /**
     * Creates new form Seguimiento
     */
    void LlenarComboBoxNombre() {
        Conexion ConexionComboBox = new Conexion().conectar();
        String consulta = "SELECT CONCAT(Nombre,' ',Apellidos) as Concatenacion FROM c_datosgenerales;";
        ResultSet Rs = ConexionComboBox.consultar(consulta);
        AutoCompleteDecorator.decorate(jComboBoxNombre);
        try {
            while (Rs.next()) {
                jComboBoxNombre.addItem(Rs.getString("Concatenacion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void Buscar(String texto) {
        //where concat(Folio,Nombre,apellidos,Direccion,ciudad,FechaNacimiento,telefono,Puesto,FechaContratacion) like '%" + texto + "%'"
        String Folio = "SELECT Fecha,Estatura,Peso,IMC,CONCAT(Nombre, ' ',Apellidos) AS Nombre, edad,FechaInscripcion"
                + " FROM c_datosgenerales,seguimiento WHERE c_datosgenerales.IDCliente ="
                + "(SELECT IDCliente FROM c_datosgenerales WHERE CONCAT(Nombre, ' ',Apellidos)='"
                + texto + "') AND c_datosgenerales.`IDCliente`=Seguimiento.`IDCliente`;";
        
        Conexion baseDatos = new Conexion().conectar();
        System.out.println(Folio);
        String[] Titulos = {"FECHA", "ESTATURA", "PESO", "IMC"};
        String[] Datos = new String[Titulos.length];
        Modelo = new DefaultTableModel(null, Titulos);

        ResultSet resultados = baseDatos.consultar(Folio);
        String NombreString = "";
        String Edad = "";
        String FechaInscripcion = "";

        try {
            while (resultados.next()) {
                for (int i = 0; i < Datos.length; i++) {
                    Datos[i] = resultados.getString(i + 1);
                    System.out.println("Datos[" + i + "] = " + resultados.getString(i + 1) + " Posición " + (i + 1));
                }
                Modelo.addRow(Datos);
                NombreString = resultados.getString("Nombre");
                Edad = resultados.getString("edad");
                FechaInscripcion = resultados.getString("FechaInscripcion");
            }
            TablaSeguimiento.setModel(Modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "qqqq");
        }

        txtSeguimientoD.setText(NombreString);
        txtEdad.setText(Edad);
        txtFecha.setText(FechaInscripcion);
    }
    

    String Fecha(Calendar F) {
        int año = F.get(Calendar.YEAR);
        int mes = F.get(Calendar.MONTH) + 1;
        int dia = F.get(Calendar.DAY_OF_MONTH);
        int hora = F.get(Calendar.HOUR_OF_DAY);
        int minuto = F.get(Calendar.MINUTE);
        int segundo = F.get(Calendar.SECOND);
        String FechaHoy = dia + "/";
        if (mes < 10) {
            FechaHoy = FechaHoy + "0" + mes + "/" + año;
        } else {
            FechaHoy = FechaHoy + mes + "/" + año;
        }
        return FechaHoy;
    }

    public Seguimiento() {
        initComponents();
        LlenarComboBoxNombre();
        //jLabel5.setText(Login.UsuarioLogueado);
        btnAgregar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSeguimiento = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabelSeguimientoD = new javax.swing.JLabel();
        txtSeguimientoD = new javax.swing.JTextField();
        btnRegresarS = new javax.swing.JButton();
        jComboBoxNombre = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();

        jLabelEdad.setText("Edad:");

        jLabelFecha.setText("Fecha de inscripción:");

        TablaSeguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSeguimiento);

        jLabelNombre.setText("Nombre del Cliente:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarbtn40.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabelSeguimientoD.setText("Seguimiento de:");

        txtSeguimientoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguimientoDActionPerformed(evt);
            }
        });

        btnRegresarS.setText("Regresar");
        btnRegresarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarSActionPerformed(evt);
            }
        });

        jComboBoxNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNombreItemStateChanged(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresarS)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeguimientoD)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelNombre))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSeguimientoD, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeguimientoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeguimientoD, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnRegresarS)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeguimientoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguimientoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguimientoDActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar(jComboBoxNombre.getSelectedItem().toString());
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarSActionPerformed
        dispose();

    }//GEN-LAST:event_btnRegresarSActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        float Peso = Float.parseFloat(JOptionPane.showInputDialog(null, "Inserta el Peso: ", "Insertar Peso"));
        float Estatura = Float.parseFloat(JOptionPane.showInputDialog(null, "Inserta la Estatura : ", "Insertar Estatura"));
        String IDCliente = "";
        Calendar FechaDeHoy = Calendar.getInstance();
        String Fecha = Fecha(FechaDeHoy);
        String IMC = String.valueOf(Peso / (Estatura * Estatura));
        String ConsultaIDCliente = "SELECT IDCliente FROM c_datosgenerales WHERE CONCAT(Nombre, ' ',Apellidos)='"
                + jComboBoxNombre.getSelectedItem().toString() + "'";
        Conexion basedatos = new Conexion().conectar();
        ResultSet rs = basedatos.consultar(ConsultaIDCliente);

        try {
            while (rs.next()) {
                IDCliente = rs.getString("IDCliente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Seguimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        Conexion basedatos1 = new Conexion().conectar();
        String Insertar = "Insert into Seguimiento values('" + IDCliente + "','" + Fecha + "','" + Estatura + "','" + Peso + "','" + IMC + "')";
        if (basedatos1.ejecutar(Insertar)) {
            JOptionPane.showMessageDialog(null, "Se ha insertado Exitosamente");
        }
        Buscar(jComboBoxNombre.getSelectedItem().toString());

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jComboBoxNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNombreItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Buscar(jComboBoxNombre.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBoxNombreItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSeguimiento;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresarS;
    private javax.swing.JComboBox<String> jComboBoxNombre;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSeguimientoD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtSeguimientoD;
    // End of variables declaration//GEN-END:variables
}
