package gimnasio;

import static gimnasio.Productos.Modelo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class Usuarios extends javax.swing.JFrame {

    void LlenarComboBox() {
        Conexion ConexionComboBox = new Conexion().conectar();
        String consulta = "Select Descripcion from puestos";
        ResultSet Rs = ConexionComboBox.consultar(consulta);
        try {
            while (Rs.next()) {
                ComboBoxPuesto.addItem(Rs.getString("Descripcion"));
                System.out.println(Rs.getString("Descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public boolean ValidarCasillas() {
        boolean confirm = true;
        if (txtIDU.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "ID campo vacio");
        } else if (jComboBoxNombre.getSelectedItem().toString().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "NOMBRE campo vacio");
        } else if (txtUsuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "TAMAÑO campo vacio");
        } else if (jComboBoxTipoUserM.getSelectedItem().toString().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Tipo de usuario campo vacio");
        }else if (jPasswordContrasenia.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "STOCK campo vacio");
        } else if (jPasswordConfirmarContra.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "PRECIO campo vacio");
        } else {
            confirm = false;
        }
        return confirm;
    }
    public void RellenarTabla() {
        Conexion baseDatos = new Conexion().conectar();
        String[] Titulos = {"ID", "NOMBRE ", "APELLIDOS", "USUARIO ", "CONTRASEÑA", "TIPO DE USUARIO"};
        String[] Datos = new String[Titulos.length];
        Modelo = new DefaultTableModel(null, Titulos);
        ResultSet resultados = baseDatos.consultar("SELECT * FROM USUARIOS");
        if (resultados != null) {
            try {
                while (resultados.next()) {
                    for (int i = 0; i < Datos.length; i++) {
                        Datos[i] = resultados.getString(i + 1);
                    }
                    Modelo.addRow(Datos);
                }
                TablaUsuarios.setModel(Modelo);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e + "qqqq");
            }
        } else {
            System.out.println("No hay Datos insertados");
            JOptionPane.showMessageDialog(this, "No hay datos insertados en la tabla", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public void BorrarDatos() {
        txtIDU.setText("");
        txtUsuario.setText("");
        jPasswordContrasenia.setText("");
        jPasswordConfirmarContra.setText("");
    }

    public Usuarios() {
        initComponents();
        btnEliminar.setEnabled(false);
        btnIrModificar.setEnabled(false);
        PanelPrincipal.remove(2);
        PanelPrincipal.remove(1);
        RellenarTabla();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JTabbedPane();
        PanelUsuario = new javax.swing.JPanel();
        Usuarios = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnIrModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        btnIrCrear = new javax.swing.JButton();
        PanelCrear = new javax.swing.JPanel();
        CrearUsuario = new javax.swing.JLabel();
        jLabelIDU = new javax.swing.JLabel();
        txtIDU = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jComboBoxNombre = new javax.swing.JComboBox<>();
        jLabelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelContrasenia = new javax.swing.JLabel();
        jPasswordContrasenia = new javax.swing.JPasswordField();
        jLabelConfirmarC = new javax.swing.JLabel();
        jPasswordConfirmarContra = new javax.swing.JPasswordField();
        btnCrearUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        ComboBoxPuesto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        PanelModificar = new javax.swing.JPanel();
        jLabelIDM = new javax.swing.JLabel();
        txtIDM = new javax.swing.JTextField();
        jLabelNombreM = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        txtUsuarioM = new javax.swing.JTextField();
        jLabelUsuarioM = new javax.swing.JLabel();
        jLabelContraseniaM = new javax.swing.JLabel();
        jLabelTipoUserM = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnCerrarMod = new javax.swing.JButton();
        jPasswordContraseniaM = new javax.swing.JPasswordField();
        ModificarUsuario = new javax.swing.JLabel();
        jComboBoxTipoUserM = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de usuarios");

        PanelPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelPrincipalKeyPressed(evt);
            }
        });

        Usuarios.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        Usuarios.setText("Usuarios");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnIrModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModificarUsuario.png"))); // NOI18N
        btnIrModificar.setText("Modificar");
        btnIrModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EliminarUsuarioIcono.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        btnIrCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarIcono.png"))); // NOI18N
        btnIrCrear.setText("Crear");
        btnIrCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnIrCrear)
                        .addGap(29, 29, 29)
                        .addComponent(btnIrModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrar)
                            .addComponent(btnEliminar)
                            .addComponent(btnIrModificar)
                            .addComponent(btnIrCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(282, 282, 282))))
        );

        PanelPrincipal.addTab("Usuarios", PanelUsuario);

        PanelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCrearMouseClicked(evt);
            }
        });
        PanelCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelCrearKeyPressed(evt);
            }
        });

        CrearUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        CrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newUser.png"))); // NOI18N
        CrearUsuario.setText("Crear Usuario");

        jLabelIDU.setText("IDUsuario:");

        txtIDU.setEditable(false);
        txtIDU.setText(" ");

        jLabelNombre.setText("Nombre:");

        jLabelUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabelContrasenia.setText("Contraseña:");

        jLabelConfirmarC.setText("Confirmar Contraseña:");

        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newUserIcono.png"))); // NOI18N
        btnCrearUsuario.setText("Agregar");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        jLabel2.setText("Tipo de Usuario: ");

        javax.swing.GroupLayout PanelCrearLayout = new javax.swing.GroupLayout(PanelCrear);
        PanelCrear.setLayout(PanelCrearLayout);
        PanelCrearLayout.setHorizontalGroup(
            PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearLayout.createSequentialGroup()
                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCrearLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCrearLayout.createSequentialGroup()
                                .addComponent(jLabelContrasenia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelConfirmarC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCrearLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnCrearUsuario)
                                .addGap(70, 70, 70)
                                .addComponent(btnCancelar))
                            .addGroup(PanelCrearLayout.createSequentialGroup()
                                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCrearLayout.createSequentialGroup()
                                        .addComponent(jLabelIDU)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtIDU, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelNombre))
                                    .addGroup(PanelCrearLayout.createSequentialGroup()
                                        .addComponent(jLabelUsuario)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelCrearLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        PanelCrearLayout.setVerticalGroup(
            PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearUsuario)
                .addGap(5, 5, 5)
                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDU)
                    .addComponent(jLabelNombre)
                    .addComponent(jComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelUsuario)))
                .addGap(18, 18, 18)
                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasenia)
                    .addComponent(jPasswordContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConfirmarC)
                    .addComponent(jPasswordConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(PanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUsuario)
                    .addComponent(btnCancelar))
                .addGap(32, 32, 32))
        );

        PanelPrincipal.addTab("Crear Usuario", PanelCrear);

        PanelModificar.setEnabled(false);
        PanelModificar.setFocusable(false);
        PanelModificar.setRequestFocusEnabled(false);

        jLabelIDM.setText("IDUsuario:");

        txtIDM.setEditable(false);
        txtIDM.setText(" ");

        jLabelNombreM.setText("Nombre:");

        txtNombreM.setText(" ");

        txtUsuarioM.setText(" ");

        jLabelUsuarioM.setText("Usuario:");

        jLabelContraseniaM.setText("Contraseña:");

        jLabelTipoUserM.setText("Tipo de Usuario:");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModificarUsuario.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrarMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar.png"))); // NOI18N
        btnCerrarMod.setText("Cerrar");
        btnCerrarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarModActionPerformed(evt);
            }
        });

        ModificarUsuario.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        ModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModificarUsuarioPantalla.png"))); // NOI18N
        ModificarUsuario.setText("Modificar");

        jComboBoxTipoUserM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Encargado", "Instructor" }));

        javax.swing.GroupLayout PanelModificarLayout = new javax.swing.GroupLayout(PanelModificar);
        PanelModificar.setLayout(PanelModificarLayout);
        PanelModificarLayout.setHorizontalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addComponent(ModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addComponent(jLabelIDM)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelModificarLayout.createSequentialGroup()
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombreM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsuarioM, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtIDM, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsuarioM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContraseniaM)
                            .addComponent(jLabelTipoUserM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordContraseniaM)
                            .addComponent(jComboBoxTipoUserM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrarMod))
                .addContainerGap())
        );
        PanelModificarLayout.setVerticalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIDM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuarioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuarioM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContraseniaM)
                            .addComponent(jPasswordContraseniaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoUserM)
                            .addComponent(jComboBoxTipoUserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(26, 26, 26)
                        .addComponent(btnCerrarMod)))
                .addGap(62, 62, 62))
        );

        PanelPrincipal.addTab("Modificar", PanelModificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnIrModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrModificarActionPerformed
        PanelPrincipal.addTab("Modificar", PanelModificar);
        PanelPrincipal.setSelectedIndex(2);

    }//GEN-LAST:event_btnIrModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        PanelPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarModActionPerformed
        PanelPrincipal.setSelectedIndex(0);
        PanelPrincipal.remove(2);
    }//GEN-LAST:event_btnCerrarModActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            Conexion basedatos = new Conexion().conectar();
            int fila = TablaUsuarios.getSelectedRow();
            String IDP = TablaUsuarios.getValueAt(fila, 0).toString();
            System.out.println(IDP);
            String Nom = TablaUsuarios.getValueAt(fila, 1).toString();
            System.out.println(Nom);
            int confirmado = JOptionPane.showConfirmDialog(null,
                    "Seguro de eliminar el Usuario '" + Nom + "'", "Confirmar eliminación",
                    JOptionPane.OK_OPTION);

            if (JOptionPane.OK_OPTION == confirmado) {
                String Eliminar = "DELETE FROM Usuario WHERE IDUser = '" + IDP + "'";
                System.out.println(Eliminar);
                if (basedatos.ejecutar(Eliminar)) {
                    JOptionPane.showMessageDialog(null, "Registro Eliminado");

                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema al Eliminar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se elimino el Usuario");
            }

        } catch (Exception e) {
            System.out.println(e.getCause());
        }
        TablaUsuarios.clearSelection();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        if (evt.getButton() == 1) {
            int fila = TablaUsuarios.getSelectedRow();
            if (fila >= 0) {
                btnEliminar.setEnabled(true);
                btnIrModificar.setEnabled(true);
            } else {
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
                JOptionPane.showMessageDialog(null, "No se ha seleccionado nada");
            }
        }
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void PanelPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelPrincipalKeyPressed
    }//GEN-LAST:event_PanelPrincipalKeyPressed

    private void btnIrCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCrearActionPerformed
        Conexion basededatos = new Conexion().conectar();
        ResultSet resultado = basededatos.consultar("SELECT IDUser from Usuarios");

        try {
            int a = 0;
            if (resultado.last()) {
                String b = resultado.getString("IDUser");
                a = Integer.parseInt(b) + 1;
                txtIDU.setText(String.valueOf(a));
            }
            System.out.println(a);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelPrincipal.addTab("Crear Usuario", PanelCrear);
        PanelPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnIrCrearActionPerformed

    private void PanelCrearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelCrearKeyPressed

    }//GEN-LAST:event_PanelCrearKeyPressed

    private void PanelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCrearMouseClicked

    }//GEN-LAST:event_PanelCrearMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        if (ValidarCasillas() == false) {
            String ID = txtIDU.getText();
            String Nombre = (String)jComboBoxNombre.getSelectedItem();
            String Usuario = txtUsuario.getText();
            String TipoUser = (String) jComboBoxTipoUserM.getSelectedItem();
            String Contrasenia1 = jPasswordContrasenia.getText();
            String ConfirContr = jPasswordConfirmarContra.getText();
            System.out.println(ID+" "+ Nombre+ " "+Usuario+" "+TipoUser+" "+Contrasenia1+" "+ConfirContr);
            Conexion basedatos = new Conexion().conectar();
            String Consulta = "select nombre,apellidos from c_datosgenerales where concact(nombre,apellidos) like '"+Nombre+"'";
            ResultSet Rs = basedatos.consultar(Consulta);
            String NombreInsert="",ApellidosInsert = "";
            try {
                while(Rs.next()){
                    NombreInsert = Rs.getString("nombre");
                    ApellidosInsert=Rs.getString("Apellidos");
                }
            } catch (Exception e) {
            }
            if (!Contrasenia1.equals(ConfirContr)) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }else{
                String Contrasenia = jPasswordContrasenia.getText();
                Conexion basedatos1 = new Conexion().conectar();
                String Insertar = "INSERT INTO Usuarios VALUES('" + ID + "','" + NombreInsert + "','"+ApellidosInsert+"','" + Usuario + "','" + Contrasenia + "','" + TipoUser + "');";
                System.out.println(Insertar);
                if (basedatos1.ejecutar(Insertar)) {
                    JOptionPane.showMessageDialog(null, "Usuario agregado");

                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema al Agregar el Usuario");
                }
                PanelPrincipal.setSelectedIndex(0);
                PanelPrincipal.remove(1);
                BorrarDatos();
                RellenarTabla();
            }

        }
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
        } catch (Exception e){
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPuesto;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JLabel ModificarUsuario;
    private javax.swing.JPanel PanelCrear;
    private javax.swing.JPanel PanelModificar;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JLabel Usuarios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrarMod;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrCrear;
    private javax.swing.JButton btnIrModificar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> jComboBoxNombre;
    private javax.swing.JComboBox<String> jComboBoxTipoUserM;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConfirmarC;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelContraseniaM;
    private javax.swing.JLabel jLabelIDM;
    private javax.swing.JLabel jLabelIDU;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreM;
    private javax.swing.JLabel jLabelTipoUserM;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuarioM;
    private javax.swing.JPasswordField jPasswordConfirmarContra;
    private javax.swing.JPasswordField jPasswordContrasenia;
    private javax.swing.JPasswordField jPasswordContraseniaM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIDM;
    private javax.swing.JTextField txtIDU;
    private javax.swing.JTextField txtNombreM;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioM;
    // End of variables declaration//GEN-END:variables
}
